### Numpy

Numpy: allows to perform advanced mathematical and statistical operations on the object.
       It provides vectorization of mathematical operations on arrays and matrices.
        Pandas built on numpy.  

#To install packages

pip install package name

conda install package name

In [1]:
#Numpy:
#Creating Numpy Arrays 
import numpy as np



In [3]:
array_1d=np.array([1,2,3,4])
array_2d=np.array([[1,2,3],[4,5,6]])
print(array_1d)
print(array_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [5]:
#Find Shape of the array
array_2d.shape

(2, 3)

In [6]:
#Number of Dimensions
print(array_2d.ndim)
print(array_1d.ndim)

2
1


In [7]:
##creating numpy array using numpy.arange
array_1d=np.arange(5)
array_1d

array([0, 1, 2, 3, 4])

In [9]:
#creating numpy array using numpy.arange
array_2d=np.arange(2,10,2)
array_2d

array([2, 4, 6, 8])

In [10]:
##Numpy array creation via various functions

##numpy.zeros, numpy.ones, numpy.eye, nrandom.rand
##numpy.ones
array_4=np.ones((2,3))
array_4


array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
##numpy.zeros
array_5=np.zeros((2,3))
array_5


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arra=np.eye(2,3)
arra

array([[1., 0., 0.],
       [0., 1., 0.]])

In [17]:
##numpy.random.rand
##Using the rand, randn functions
#rand(m) produces uniformly distributed random numbers with range 0 to m
np.random.seed(200)
array_8=np.random.rand(4)
array_8


array([0.94763226, 0.22654742, 0.59442014, 0.42830868])

In [18]:
array_8=np.random.rand(4)
array_8

array([0.76414069, 0.00286059, 0.35742368, 0.90969489])

In [21]:
arr_11=np.array([10,11,12,13])
print(arr_11.dtype)
print(type(arr_11))
print(arr_11)

int32
<class 'numpy.ndarray'>
[10 11 12 13]


In [22]:
#change the data type 
arr_11=arr_11.astype(float)
arr_11.dtype

dtype('float64')

In [ ]:
##NumPy indexing and slicing

##Array indices in NumPy start at 0

#import numpy as np


#print entire array


In [20]:
arr_1=np.arange(6)
arr_1

array([0, 1, 2, 3, 4, 5])

In [23]:
arr_1[2]

2

In [24]:
arr_1[4]

4

In [25]:
arr_1[:]

array([0, 1, 2, 3, 4, 5])

In [26]:
arr_1[2:5]

array([2, 3, 4])

In [27]:
#last element
arr_1[-1]

5

In [28]:
##Modify value at arr_1[1]
arr_1[-1]=7
arr_1[:]

array([0, 1, 2, 3, 4, 7])

In [31]:
array_2d=np.array([[1,2,3],[4,5,6]])
array_2d
array_2d[0,0]

1

In [ ]:
#[row,column]
#extract 2nd row, 3rd column value : 90

In [35]:
array_3=np.array ([[10,20,30],[40,50,90],[35,65,76],[90,80,70],[23,34,56]])
array_3


array([[10, 20, 30],
       [40, 50, 90],
       [35, 65, 76],
       [90, 80, 70],
       [23, 34, 56]])

In [40]:
#extract the value 80
array_3[3,1]

80

In [ ]:
#extract 2nd position column values


#### ARITHMETIC OPERATIONS

In [42]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])


In [43]:
print(np.add(arr1,arr2))

[[ 8 10 12]
 [14 16 18]]


In [ ]:
#Subtract two array

In [48]:
print(np.subtract(arr2,arr1))

[[6 6 6]
 [6 6 6]]


In [ ]:
#Multiply

In [49]:
print(np.multiply(arr1,arr2))

[[ 7 16 27]
 [40 55 72]]


In [ ]:
#Division

In [51]:
print(np.divide(arr1,arr2))

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [62]:
# power 4
arr_2=np.arange(1,10)**4
arr_2

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [63]:
#sqrt
arr_2=np.sqrt([10,12])
arr_2

array([3.16227766, 3.46410162])

In [ ]:
#Operations also work element-wise when another array is the second operand as follows:
arr_4=np.arange(0,20,2)


In [ ]:
##we see element-wise subtraction, division, and multiplication:
##SUBTRACTION
arr_5=np.arange(0,10)



In [ ]:
##MULTIPLICATION


In [68]:
##MATRIX MULTIPLICATION
arr_9=np.array([[5,5],[5,5]])


arr_10=np.array([[7,7],[7,7]])

arr_11=arr_9.dot(arr_10)
print(arr_11)




[[70 70]
 [70 70]]


In [2]:
#transpose
#transpose method (.T)
import numpy as np
arr_20=np.array([[1,2,3],[4,5,6]]) 
arr_21=arr_20.T
print(arr_20)
print(arr_21)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [3]:
#np.transpose()
arr_21=np.transpose(arr_20)
arr_21

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
#### Array_shape_manipulation

In [6]:
## FLATTENING A MULTI_DIMENSIONAL ARRAY

##np.ravel() - flatten a multi-dimensional array

arr_1=np.array([np.arange(2,7), np.arange(15,20)])
arr_1


array([[ 2,  3,  4,  5,  6],
       [15, 16, 17, 18, 19]])

In [8]:
arr_1.ndim

2

In [11]:
arr_2=arr_1.ravel()
arr_2

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [12]:
##RESHAPING
#reshape(row,col)
arr_3=np.arange(11,26)
arr_3.reshape(3,5)


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
##RESIZING
##numpy.ndarray.resize
arr_5=np.arange(10,15)
print(arr_5)
arr_5.resize((8,2))

[10 11 12 13 14]


In [ ]:
# difference between np.resize() and resize() method.

In [14]:
#It doesn't allow to resize if there are any other references
arr_6=np.arange(10,15)
arr_7=arr_6
print(arr_7)
arr_7.resize((8,))

[10 11 12 13 14]


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [23]:
arr=np.array([2,4,7,9,13,16,20,24,27,29,33,35])

In [24]:
#Convert reshape from 1d to 2d
arr2=arr.reshape(4,3)
arr2

array([[ 2,  4,  7],
       [ 9, 13, 16],
       [20, 24, 27],
       [29, 33, 35]])

In [22]:
#Convert 1d to 3d using numpy.reshape()
arr3=np.reshape(arr(2,2,3))
arr3

TypeError: 'numpy.ndarray' object is not callable